train_csv_path: "data/train_images.csv"
train_dir_path: "data/train_images"
test_csv_path: "data/test_images_path.csv"
test_dir_path: "data/test_images"
attributes_path: "data/attributes.npy"
class_names_path: "data/class_names.npy"
submission_dir: "experiments/submissions"
models_dir: "experiments/models"
checkpoints_dir: "experiments/checkpoints"
model_type: "vit"
vit_model: "google/vit-large-patch16-224"
num_classes: 200
attribute_dim: 312
batch_size: 16
num_epochs: 100
learning_rate: 0.0001
weight_decay: 0.0001
resize_size: [224, 224]
val_size: 0.2
label_smoothing: 0.1
num_workers: 4
scheduler_patience: 5
scheduler_factor: 0.2
early_stopping_patience: 10
use_sampler: false
use_custom_split: true
use_adamw: true
use_focal_loss: false
use_cosine_scheduler: true
unfreeze_layers: 3
